import type { SidenoteState } from './types.js';

const NOW = Date.UTC(2026, 9, 2, 6, 11, 0);

export function createDemoState(): SidenoteState {
  return {
    seeded: true,
    pages: [
      {
        id: 'page-google',
        title: 'Google',
        url: 'https://www.google.com/',
        patterns: [],
        ignoreQuery: true,
        tags: [],
        updatedAt: NOW,
      },
      {
        id: 'page-drive',
        title: 'Google Drive',
        url: 'https://drive.google.com/',
        patterns: [],
        ignoreQuery: true,
        tags: [],
        updatedAt: NOW,
      },
      {
        id: 'page-gmail',
        title: 'Gmail',
        url: 'https://mail.google.com/',
        patterns: [],
        ignoreQuery: true,
        tags: ['mail'],
        updatedAt: NOW,
      },
      {
        id: 'page-chatgpt',
        title: 'ChatGPT',
        url: 'https://chatgpt.com/',
        patterns: [],
        ignoreQuery: true,
        tags: [],
        updatedAt: NOW,
      },
      {
        id: 'page-bbc',
        title: "Meta's new AI Muse",
        url: 'https://www.bbc.com/future/article/20260930-metas-new-ai-is-about-to-break-the-internet',
        patterns: ['bbc.com/future/*'],
        ignoreQuery: true,
        tags: ['muse'],
        updatedAt: NOW,
      },
    ],
    notes: [
      {
        id: 'note-bbc',
        pageId: 'page-bbc',
        text: 'Agents can book and buy without looking at the ads. Worth a journal entry.',
        visibility: 'private',
        collectionId: 'col-reading',
        keywords: ['muse'],
        anchor: { selector: 'article', offset: 120, textQuote: 'Agents can book and buy' },
        createdAt: NOW - 3600_000,
        updatedAt: NOW - 600_000,
      },
      {
        id: 'note-gmail',
        pageId: 'page-gmail',
        text: 'Send the Friday reply before noon.',
        visibility: 'group:group-home',
        collectionId: 'col-inbox',
        keywords: ['mail'],
        anchor: { selector: 'body', offset: 20 },
        createdAt: NOW - 7200_000,
        updatedAt: NOW - 7200_000,
      },
    ],
    excerpts: [
      {
        id: 'excerpt-read',
        scope: {
          url: 'https://www.bbc.com/future/article/20260930-metas-new-ai-is-about-to-break-the-internet',
          pageId: 'page-bbc',
          key: 'bbc.com/future/article/20260930-metas-new-ai-is-about-to-break-the-internet',
        },
        userAction: 'read',
        text: 'Read to 40% · The Swiftie problem',
        excerpt: 'Agents can book, buy, and pester a site faster than a person.',
        meta: { depth: 0.4, section: 'The Swiftie problem', durationMs: 90_000 },
        createdAt: NOW - 1800_000,
        updatedAt: NOW - 1800_000,
      },
      {
        id: 'excerpt-select',
        scope: {
          url: 'https://www.bbc.com/future/article/20260930-metas-new-ai-is-about-to-break-the-internet',
          pageId: 'page-bbc',
          key: 'bbc.com/future/article/20260930-metas-new-ai-is-about-to-break-the-internet',
        },
        userAction: 'select',
        text: 'Selected a line about ticket bots',
        excerpt: 'Everyone can have a personal scalper bot.',
        range: {
          selector: 'article p',
          startOffset: 0,
          endOffset: 42,
          textQuote: 'Everyone can have a personal scalper bot.',
        },
        meta: { section: 'The Swiftie problem' },
        createdAt: NOW - 900_000,
        updatedAt: NOW - 900_000,
      },
    ],
    collections: [
      {
        id: 'col-reading',
        name: 'Reading',
        visibility: 'private',
        updatedAt: NOW - 600_000,
      },
      {
        id: 'col-inbox',
        name: 'Inbox',
        visibility: 'private',
        updatedAt: NOW - 7200_000,
      },
    ],
    projects: [
      {
        id: 'proj-sidenote',
        name: 'Sidenote',
        color: '#c9a35a',
        order: 0,
        updatedAt: NOW,
      },
    ],
    tasks: [
      {
        id: 'task-muse',
        localNo: 2,
        title: 'Map the Muse note into a journal entry',
        projectId: 'proj-sidenote',
        status: 'draft',
        due: '2026-10-06',
        refUrl: 'https://www.bbc.com/future/article/20260930-metas-new-ai-is-about-to-break-the-internet',
        updatedAt: NOW - 600_000,
      },
      {
        id: 'task-mail',
        localNo: 1,
        title: 'Clear the school thread',
        projectId: null,
        status: 'active',
        due: '2026-10-04',
        refUrl: 'https://mail.google.com/',
        updatedAt: NOW - 7200_000,
      },
    ],
    tags: [
      { id: 'tag-muse', name: 'muse', visibility: 'private', updatedAt: NOW },
      { id: 'tag-mail', name: 'mail', visibility: 'group:group-home', updatedAt: NOW },
    ],
    groups: [
      {
        id: 'group-home',
        name: 'Home',
        handle: 'home',
        readAccess: true,
        status: 'active',
        updatedAt: NOW,
      },
      {
        id: 'group-work',
        name: 'Work',
        handle: 'work',
        readAccess: false,
        status: 'inactive',
        updatedAt: NOW,
      },
    ],
    settings: {
      language: 'en',
      timeZone: 'Asia/Seoul',
      theme: 'system',
      display: { collections: 10, notesPerCollection: 3, tasks: 10 },
      accountEmail: '',
    },
    ui: {
      expanded: false,
      sections: {
        about: true,
        notes: true,
        history: true,
        collections: true,
        globalHistory: true,
        tasks: true,
        settings: true,
      },
      noteSort: 'time',
      historyFilter: 'all',
      collectionSort: 'recency',
      taskSort: 'recency',
      historyShown: 10,
      collectionsShown: 10,
      tasksShown: 10,
      openCollections: ['col-reading'],
      openProjects: ['proj-sidenote', 'uncategorized'],
      openSettings: ['account'],
      treeOpen: [],
    },
  };
}
